# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ImageViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageViewer
  pod 'ReachabilitySwift'

  target 'ImageViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageViewerUITests' do
    # Pods for testing
  end

end
